### ISSUE TITLE
Add configuration option to hide preview by default

### ISSUE THREAD

**Issue by Spreizu** [pemedia/payload-visual-editor#11]
Hi!

Thank you very much for this plugin. I just tried playing around with it and realised that there does not seem to be an option to disable preview by default. Would it be possible to add this simple configuration option so that the class would not be set unless "Live preview" is clicked by the user?

Thanks in advance and again, thanks for this great plugin!

**Comment by jpeiniger** [comment]
Hi @Spreizu! Thanks for the input!
That sounds like a nice idea for an optional config setting. I'll look into it in the coming days.
