### ISSUE TITLE
Layout issues when versions are enabled

### ISSUE THREAD

**Issue by qbeauperin** [pemedia/payload-visual-editor#14]
With versions and drafts enabled, the new layout has some issues:

- Publish button goes over two lines
![image](https://github.com/pemedia/payload-visual-editor/assets/1763338/9c7b1a64-70dc-4127-a861-0c07fb4d8102)
- The status and the "unpublish" / "revert to published" buttons are missing
![image](https://github.com/pemedia/payload-visual-editor/assets/1763338/c115c33e-d72b-44e0-a18f-9d774890a904)
- "Versions", "Last modified", and "Created" meta sections are missing as well
![image](https://github.com/pemedia/payload-visual-editor/assets/1763338/91e2bdca-e978-439a-b7c2-24c8c8a12ef6)

**Comment by jpeiniger** [comment]
Thanks for the report. I hope I fixed all this in the coming release. Probably available in a few days.

**Comment by jpeiniger** [comment]
should be fixed with #12

**Comment by qbeauperin** [comment]
Woooo you rock! 🤘
