### ISSUE TITLE
fetchRelation is not respecting custom api routes

### ISSUE THREAD

**Issue by Void-E** [pemedia/payload-visual-editor#18]
When having the `api` path on a different route (via payload.config.ts), the fetchRelation method (https://github.com/pemedia/payload-visual-editor/blob/main/src/utils/generateDocument.ts#L30) has a hardcoded path to `api`.

In my application the path is rewritten to `_api` to avoid conflicts with NextJS, so the visual editor fails fetching requests.

**Comment by jpeiniger** [comment]
This should be fixed now. Feel free to try it out @Void-E

**Comment by Void-E** [comment]
Just downloaded the new release and it works like a charm! Thanks for the quick resolution!
