### ISSUE TITLE
Admin left sidebar is still visible

### ISSUE THREAD

**Issue by anthonyivol** [pemedia/payload-visual-editor#21]
I have installed the plugin in a fresh payload install, and I should have missed something but the left sidebar is still visible so I can't get enough space for the preview. 
I looked into the  scss and there is nothing about the nav, is it still in development ?
Thanks !

**Comment by dkirchhof** [comment]
Hey, you're totally right. The toolbar doesn't shrink automatically. The screenshot doesn't reflect the example of this repo. It was made from another project where we applied some custom styling / logic to expand / collapse the toolbar.
It's maybe a bit misleading. We should change the screenshot or write a small hint.

If you're interested how we hide the toolbar, feel free to ask.
