### ISSUE TITLE
Feature: Trigger reload on save

### ISSUE THREAD

**Issue by silveltman** [pemedia/payload-visual-editor#23]
Feature request: option to trigger reload of the preview domain on save.

Why? When using Astro for example and the build is fully static, live updating the variables does not work. It's however very easy to run Astro on SSR mode on the editing domain, and on 'static' mode on the production domain. This way astro automatically uses new values on reload.

**Comment by dkirchhof** [comment]
Probably we will stop working on this plugin and try to contribute to the built-in live preview feature in payload 2.0.
If your request wasn't considered there, you should create the feature request in the payload repo as well.

**Comment by silveltman** [comment]
For people landing here, I ended up making the following svelte component in my Astro project which only gets rendered on the preview branche:

```
<script lang="ts">
  import { subscribe, unsubscribe } from '@payloadcms/live-preview';
  import { navigate } from 'astro:transitions/client';
  import { onMount, onDestroy } from 'svelte';

  const serverURL = import.meta.env.PUBLIC_PAYLOAD_SERVER_URL;
  const depth = 2;
  let initialData = null;
  let data = initialData;
  let subscription;
  let changes = 0;
  let lastUpdate;

  const onChange = (mergedData) => {
    const currentUpdate = mergedData.updatedAt;
    if (lastUpdate && lastUpdate !== currentUpdate) {
      navigate(`/contact?count=${changes}`);
    }
    lastUpdate = currentUpdate;
    data = mergedData;
    changes++;
  };

  onMount(() => {
    subscription = subscribe({
      callback: onChange,
      depth,
      initialData,
      serverURL,
    });
  });

  onDestroy(() => {
    unsubscribe(subscription);
  });
</script>
```

It utilizes Astro's view transitions API to make the reaload seamless. It reloads te page on save, based on the changing updatedAt key.
