### ISSUE TITLE
Does not work with payloadcms 2.0

### ISSUE THREAD

**Issue by TomDo1234** [pemedia/payload-visual-editor#26]
![image](https://github.com/pemedia/payload-visual-editor/assets/37052068/9c0822ec-3611-4c54-8403-7eee3dbecc3b)

**Comment by jpeiniger** [comment]
Just added a note to the README. Payload version 2 includes the live preview as a core feature, so this plugin will not be necessary anymore if you are using Payload 2.x.

**Comment by jpeiniger** [comment]
@TomDo1234 With v2.0.1 the plugin now works with Payload 2.x
Feel free to try it out. We also got some new features.

**Comment by jpeiniger** [comment]
Will close this issue
