### ISSUE TITLE
Working in local but failed when deployed to vercel

### ISSUE THREAD

**Issue by supermario12342003** [pemedia/payload-visual-editor#31]
I tried this plugin using the following config
```
visualEditor({
      previewUrl: ({ locale }: PreviewUrlParams) => {
        return `${process.env.NEXT_PUBLIC_SERVER_URL}/${locale}/preview/pages`
      },
      collections: {
        pages: {
          previewUrl: ({ locale }: PreviewUrlParams) => {
            return `${process.env.NEXT_PUBLIC_SERVER_URL}/${locale}/preview/pages`
          },
        },
      },
    })
```

it's working in local, but it does not work in vercel. I got this error when it's trying to access api/me
<img width="697" alt="Screenshot 2023-11-17 at 22 01 37" src="https://github.com/pemedia/payload-visual-editor/assets/6221160/c9ee15ed-d6c2-4319-aa09-aa384ac1fa99">

the error disappears when i remove the plugin. Is it because this plugin does not support serverless environment?

**Comment by jpeiniger** [comment]
The error is unfortunately not very informative. Are you able to pin it down to a more concrete error related to any of the plugin code?

**Comment by supermario12342003** [comment]
for now i only know that this plugin works perfectly in a non edge runtime. i deploy it in render.com and heroku, they both work perfectly, but it can't run at cloudflare page nor vercel.
