### ISSUE TITLE
Payload 2 with viteBundler stylesheet error

### ISSUE THREAD

**Issue by ericuldall** [pemedia/payload-visual-editor#34]
```
[sass] Can't find stylesheet to import.
  ╷
1 │ @import '~payload/dist/admin/scss/vars'
```

Any idea why this is missing?

**Comment by ericuldall** [comment]
Looks like removing the `~` from the front of the import name works fine. Not sure if this also works on webpack.

**Comment by dkirchhof** [comment]
No problems with webpack after removing it. Will publish a new version in a sec.
